export const FETCH_USERS_PENDING = "api/FETCH_USERS_PENDING";
export const FETCH_USERS_SUCCESS = "api/FETCH_USERS_PENDING";
export const FETCH_USERS_ERROR = "api/FETCH_USERS_ERROR";

export const FETCH_CARDS_PENDING = "api/FETCH_CARDS_PENDING";
export const FETCH_CARDS_SUCCESS = "api/FETCH_CARDS_PENDING";
export const FETCH_CARDS_ERROR = "api/FETCH_CARDS_ERROR";

export const FETCH_COURSE_PENDING = "api/FETCH_COURSE_PENDING";
export const FETCH_COURSE_SUCCESS = "api/FETCH_COURSE_PENDING";
export const FETCH_COURSE_ERROR = "api/FETCH_COURSE_ERROR";
